defaults: &cache
  key: node_cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2

jobs:
  build:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *cache
      - run:
          name: Dependencies
          command: yarn global add greenkeeper-lockfile@1
      - run:
          name: Install
          command: yarn
      - save_cache:
          <<: *cache
          paths:
            - ~/project/node_modules
      - run:
          name: Update Lockfile
          command: greenkeeper-lockfile-update
      - run:
          name: Test
          command: yarn start ci
      - run:
          name: Upload Lockfile
          command: greenkeeper-lockfile-upload
          when: on_fail
  release:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *cache
      - run:
          name: Release
          command: 'yarn release || true'
  documentation:
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *cache
      - restore_cache:
          key: docs_cache
      - run:
          name: Documentation
          command: |
            git config --global user.email "ops@groupbyinc.com"
            git config --global user.name "GroupBy Ops"
            git config --global push.default simple

            git remote rm origin
            git remote add origin "https://${GH_TOKEN}@github.com/groupby/${CIRCLE_PROJECT_REPONAME}.git"

            if [ -e component.docs.json ]; then
              mv component.docs.json old-component.docs.json
            else
              touch old-component.docs.json
            fi

            yarn docs:json
            DIFF=$(diff component.docs.json old-component.docs.json)
            if [ "$DIFF" != "" ]; then
              yarn docs
              git add docs
              git commit -m "docs: regenerate documentation" && git push -u origin master || true
            fi
      - save_cache:
          key: docs_cache
          paths:
            - ~/project/component.docs.json

workflows:
  version: 2

  build_test_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - build
      - documentation:
          filters:
            branches:
              only: master
          requires:
            - release
