fixes:
  - 'root/storefront-navigation/src/::src/'
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
